repos:
  # pre-commit hook to verify commit messages are conventional commit compliant
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.2.1
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: trailing-whitespace

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.79.1
    hooks:
      - id: terrascan
      - id: terraform_tfsec
      - id: terraform_tflint
