{
  "packages":
    {
      "modules/metadata":
        {
          "component": "metadata",
          "changelog-path": "CHANGELOG.md",
          "release-type": "terraform-module",
          "bump-minor-pre-major": true,
          "bump-patch-for-minor-pre-major": false,
          "draft": false,
          "prerelease": false,
        },
    },
  "separate-pull-requests": true,
  "pull-request-title-pattern": "chore${scope}: release${component} ${version}",
  "$schema": "https://raw.githubusercontent.com/googleapis/release-please/main/schemas/config.json",
}
